name: Update holiday

on:
  schedule:
    - cron: 30 1 * * * # JST 10:30
  workflow_dispatch:

jobs:
  updateHoliday:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.17

      - run: echo "::set-output name=date::$(date "+%Y/%m/%d")"
        id: today

      - name: run generator
        run: deno -q run --allow-net --allow-write --allow-run generator.ts

      - name: Create Pull Request (if changes exists)
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Holiday updated. (${{ steps.today.outputs.date }})'
          body: ''
